### ISSUE TITLE
Make iso workspace base dir configurable

### ISSUE THREAD

**Issue by carbonin** [diskfs/go-diskfs#100]
Currently, when building an iso, you have to create the filesystem which creates for you a workspace directory which is always in the system temp dir.

Allowing this to be configurable somehow could solve two issues:
1. I don't want to write to `/tmp`
    - Maybe I have more storage elsewhere or something faster
    - In my case specifically I want all of these writes to go to a volume rather than the container filesystem I'm running on
2. I don't want to double write all my files
    - My use case is: extract an iso to dir `x`, make changes in `x`, recreate an iso from all the files rooted at `x`
    - If I could set the workspace to `x` when creating the filesystem I would save on all the calls I'm making to recreate the whole directory tree in the workspace

As for how to solve this ... it would be tough to do both without making a breaking API change to `iso9660.Create` so I understand if we don't want to do that.
An alternative option is to create a convenience function specifically in the iso9660 package that could create and finalize an iso in one call given the workspace dir (pre-populated with the iso content), the existing parameters to `disk.Create` (or some subset) and the finalize options.

Effectively I would contribute what I have [here](https://github.com/openshift/assisted-service/blob/3bc73c1259d48b711077f5ef7de0c1fde8d066d9/internal/isoutil/isoutil.go#L130-L214) altered for general use.

@deitch what do you think? Is this something that you think would be useful or would you rather add a parameter somewhere for the workspace base dir?

**Comment by deitch** [comment]
I like where you are going with this. Two distinct but related things:

* tell iso9660 where to make its scratch space, default to system temp dir
* tell iso9660 not to create a workspace, just build from an existing one

For the first, it is straightforward. I have no issues with extending [iso9660.Create](https://pkg.go.dev/github.com/diskfs/go-diskfs@v1.1.1/filesystem/iso9660#Create) to accept an option that says to use an existing workspace directory.

Now that I think about it, if you did that, it would solve the second as well, since all of the actions on an `iso9660.FileSystem` just work on the files in the working directory, if it is there. It is _possible_ that there are parts that are cached/in-memory, but it was built not to do that.

I see only one issue, easily resolvable.

The lower-level [iso9660.Create](https://pkg.go.dev/github.com/diskfs/go-diskfs@v1.1.1/filesystem/iso9660#Create) usually is not used directly, but rather created at a higher-level. Specifically, it is called by [disk.CreateFilesystem](https://pkg.go.dev/github.com/diskfs/go-diskfs@v1.1.1/disk#Disk.CreateFilesystem), which, fortunately, _does_ take a [disk.FilesystemSpec struct](https://pkg.go.dev/github.com/diskfs/go-diskfs@v1.1.1/disk#FilesystemSpec).

The easiest path forward to me appears to be:

1. Add an option to `iso9660.Create` to take a workspace and used it, if present.
2. Add a test that uses the above and make sure it accepts files already there and works with them normally
3. Add a property to `disk.FilesystemSpec` to indicate what workspace path to use. I wouldn't name it anything iso9660-specific, as other read-only filesystems have the same property
4. Pass the workspace from `disk.FilesystemSpec` to `iso9660.Create`

It looks quite straightforward actually. I look forward to a PR on this.
