### ISSUE TITLE
Question: Can this be used to flash images to disks?

### ISSUE THREAD

**Issue by Jacalz** [diskfs/go-diskfs#138]
Hi,

Sorry if this is the wrong place to ask, but I have been trying to find a Go library that can flash ISO and IMG images. I am essentially looking for a dd alternative that can flash various Linux and BSD images. This project seems like it might be able to do that but it seems a little complicated so I am not sure if I understand it correctly.

If it can't do that currently, is there any plan on adding that functionality? Are you aware of any other libraries that do that?

**Comment by deitch** [comment]
It can, but it isn't necessary. What this does is construct the _contents_ of those ISO or IMG (and many other filesystem and disk format) images, so that you can flash them. It can write them directly to disk as well.

However, if you already _have_ ISO or IMG (raw) images, you don't need any library. You could just use [io.Copy](https://pkg.go.dev/io#Copy) to copy from your source to your disk. Something like this (untested, no real safety checks):

```go
package main

import (
    "io"
    "os"
)

func main() {
    srcFile, diskPath := os.Args[1], os.Args[2]
    src, err := os.Open(srcFile)
    // add error handling here
    defer src.Close()

    dst, err := 	os.OpenFile(diskPath, os.O_RDWR, 0755)
    // add error handling here
    defer dst.Close()

    n, err := io.Copy(dst, src)
    // add error handling here
    // add check of n bytes written, if desired
    
    // you are done
}
```

And you can run it with:

```
cmd /path/to/image.iso /dev/sda2
```

Replace `cmd` with whatever your file is compiled as, as well as your source file and destination disk

**Comment by Jacalz** [comment]
Thanks for the help. I greatly appreciate it. I guess that it assumes then that the disk is already wiped clean? Is that something that this project then could help with?

**Comment by deitch** [comment]
It does to some degree. You don't always have to wipe it clean, but you may want to. Just copy from random or from zero.

**Comment by Jacalz** [comment]
Thanks for all of the help. Much appreciated!

**Comment by Jacalz** [comment]
It worked! Massive thanks!

This is of course requiring sudo permissions. Do you know of any way to run just the write using elevated permissions? Polkit maybe? I am developing a desktop application and it's not really advisable to run the whole thing with sudo.
