### ISSUE TITLE
diskfs.Open(...) opens the file in read-only mode

### ISSUE THREAD

**Issue by a2geek** [diskfs/go-diskfs#20]
This is mostly a question on the design: I have code that opens an existing disk image with `disk, err := diskfs.Open(c.diskFileName)`. That works fine.  But as soon as I try to update a file on that disk, my code encounters write errors. Looking at the factory methods, I noticed that `diskfs.Create(...)` opens in `os.O_RDWR` mode but `diskfs.Open(...)` opens in `os.O_RDONLY` mode. 

Is there some other mechanism to open the disk/image in read-write mode to enable changes? My code is using the FAT32 filesystem, so it should be a valid use case.

For the short-term, since I have a local copy, I just updated the `diskfs.Open(...)` code.

Thanks!

**Comment by deitch** [comment]
Strangely, this was missed. I am not too surprised, since the tests all bypass that `diskfs.Open()` call, and just exercise that call to make sure it works. The writing tests are handled directly. Even the error message says `Could not open device %s exclusively for writing`:

```go
	f, err := os.OpenFile(device, os.O_RDONLY|os.O_EXCL, 0600)
	if err != nil {
		return nil, fmt.Errorf("Could not open device %s exclusively for writing", device)
	}
```

This is a valid bug, and the title is right. The change is painfully easy. Will hit when next on the laptop, maybe add a test for it... and thanks for finding it!
