### ISSUE TITLE
fat32 reads/writes incorrect 8.3 lowercase flags, should be case insensitive on fs.OpenFile

### ISSUE THREAD

**Issue by jsando** [diskfs/go-diskfs#250]
There are two distinct but related issues:

1. Lowercase filenames created with mtools are read as "lower.UPP" by go-diskfs, ie "syslinux.cfg" is read as "syslinux.CFG".  This is kind of a cosmetic issue, except for issue 2.
2. Because os.OpenFile doesn't ignore case when opening a file, the filename returned from above cannot be found (ie, attempt to open 'syslinux.CFG' as that was returned by fs.ReadDir, but get file not found instead)

Related to 2, I also added a test for mixed case on long file names in fs.OpenFile (verified on Linux vfat with "touch some-long-file && cat SOME-LONG-FILE").

I have a PR to raise for these issues, with unit tests.

**Comment by deitch** [comment]
Hi @jsando and thanks for raising this. And you opened a PR, too; we don't usually get that lucky with issues! 😄 

This is interesting. So you are saying the issue is not with diskfs _creating_ the file, as much as it is with filenames created by mtools, which then are _read_ incorrectly by diskfs?

The whole case issue with fat32 has been painful )not just here, in general) for a long time. You kind of wish they could abandon all of that 8.3 and shortnames once and for all. Of course, then it would not be fat32, would it?

If I recall correctly, the fat32 rule is that filenames can have any case (longname), as long as the 8.3 version of it (upper-case only, limited characters, etc.) do not conflict. So JASON.TXT and jason.txt cannot both exist. In other words, those are functionally the same. It has some odd ways of dealing with files that are longer than fit in 8.3, if they conflict at <= 8 chars, but that is not the subject here.

If I understood you correctly, a simple recreation would be:

1. Create a fat32 filesystem
2. Use mtools to insert a file like `syslinux.cfg` - this file would then have the long filename of `syslinux.cfg` and the shortname.extension (8.3) of `SYSLINUX.CFG`
3. Open the filesystem with diskfs and open the file as `syslinux.cfg` - this fails as file not found

Is that it?

**Comment by jsando** [comment]
You are correct on the steps to manually recreate the issue.

However step 2 is not working as you expect:  For filenames that fit within 8.3, mtools does not create a long filename, and will set the shortname.extension (8.3) to SYSLINUX.CFG, while also setting bit 3 and bit 4 of the 12th byte in the directory entry to note that both the short name and extension are lowercase.  Go-diskfs was expecting bits 2 and 3 to be set (while also hiding a bug substituting extension for name). 

Here is hexdump -C output for a directory entry written by mtools:

```
                                       Note byte 0x0c = 18
                                               👇🏻
00504040  53 59 53 4c 49 4e 55 58  43 46 47 20 18 00 84 bb  |SYSLINUXCFG ....|
00504050  17 59 17 59 00 00 84 bb  17 59 05 00 4a 00 00 00  |.Y.Y.....Y..J...|
```

Since go-diskfs is checking bit 2 for the extension instead of bit 4, it thinks the extension is uppercase and return the name 'syslinux.CFG' instead of syslinux.cfg.

**Comment by deitch** [comment]
Aha. That _does_ explain it, thank you.
