### ISSUE TITLE
iso finalize leaks the workspace temp directory

### ISSUE THREAD

**Issue by carbonin** [diskfs/go-diskfs#90]
Currently this library leaks temp directories when used as shown in the [iso_create.go example](https://github.com/diskfs/go-diskfs/blob/1236d9d5ae8d2ecdc8cd0eeee3cf7dc9d489dca7/examples/iso_create.go)

The `Finalize` method also removes the reference to the workspace, so what is the best practice here?

Should the example be changed to something like this:
```patch
diff --git a/examples/iso_create.go b/examples/iso_create.go
index c0983f8..73c6f91 100644
--- a/examples/iso_create.go
+++ b/examples/iso_create.go
@@ -33,6 +33,9 @@ func CreateIso(diskImg string) {
        if !ok {
                check(fmt.Errorf("not an iso9660 filesystem"))
        }
+       ws := fs.Workspace()
        err = iso.Finalize(iso9660.FinalizeOptions{})
        check(err)
+       err = os.RemoveAll(ws)
+       check(err)
 }
```

Or should finalize remove the workspace before it clears the reference in the filesystem struct?

I'll make whichever change you think makes more sense @deitch

**Comment by deitch** [comment]
If the temp directory were created by the example itself, I would have the temp clean it up. But it isn't; it is created by [disk.CreateFilesystem](https://github.com/diskfs/go-diskfs/blob/master/disk/disk.go#L151) which, in turn, calls [iso9660.Create()](https://github.com/diskfs/go-diskfs/blob/master/filesystem/iso9660/iso9660.go#L64) from [here](https://github.com/diskfs/go-diskfs/blob/master/disk/disk.go#L179)

`iso9660.Create()` creates the tmpdir [here](https://github.com/diskfs/go-diskfs/blob/master/filesystem/iso9660/iso9660.go#L83)

Since it is `iso9660` that creates it, it also should be responsible for removing it during `iso.Finalize()`.

**Comment by carbonin** [comment]
:+1: that's what I would prefer as well. Should have a patch up soon
